version: '3'

networks:
  in.net.ex:
    driver: bridge

services:
  products:
    build: ./products_go/
    container_name: products.in.net.ex  
    environment:
      - PATH_TO_FILE=/yandex.csv
      - DRIVER_CONFIG=yaml
    ports:
      - 8080:8080
    volumes:
      - ./products_go/internal/models/csv/yandex.csv:/yandex.csv
    networks:
      - in.net.ex

