version: '3'

# Create a proxy gateway

networks:
  in.net.ex:
    driver: bridge

services:
  backend-service:
    build: .
    container_name: backend-service.in.net.ex
    # Replace the file with the database
    environment:
      - PATH_TO_FILE=/yandex.csv
      # - DRIVER_CONFIG=yaml
    ports:
      - 8080:8080
    volumes:
      - ./internal/config/config.yaml:/config.yaml:ro
      - ./internal/models/csv/yandex.csv:/yandex.csv:ro
    depends_on:
      - backend-db.in.net.ex
    networks:
      - in.net.ex

  backend-db.in.net.ex:
      restart: always
      image: postgres:latest
      container_name: backend-db.in.net.ex
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=qwerty
        - PGDATA=/var/lib/postgresql/data/pgdata
      volumes:
        - ./sql:/docker-entrypoint-initdb.d
        # WARNING: There must be a volume here to save your database data 
      ports:
        - 5432:5432
      networks:
        - in.net.ex
